const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';

const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
const GET_MENU_FAILED = 'GET_MENU_FAILED';
const GET_MENU_ERROR = 'GET_MENU_ERROR ';

const ORDER_MEAL_SUCCESS = 'ORDER_MEAL_SUCCESS';
const ORDER_MEAL_FAILED = 'ORDER_MEAL_FAILED';
const ORDER_MEAL_ERROR = 'ORDER_MEAL_ERROR ';

export {
    START_LOADING,
    STOP_LOADING,

    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAILED,
    USER_SIGNUP_ERROR,

    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAILED,
    USER_SIGNIN_ERROR,

   
    GET_MENU_SUCCESS,
    GET_MENU_FAILED,
    GET_MENU_ERROR,

    ORDER_MEAL_SUCCESS,
    ORDER_MEAL_FAILED,
    ORDER_MEAL_ERROR
}