const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';
const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

export {
    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAILED,
    USER_SIGNUP_ERROR,
    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAILED,
    USER_SIGNIN_ERROR
}