const START_LOADING = 'START_LOADING';
const STOP_LOADING = 'STOP_LOADING';

const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
const USER_SIGNUP_FAILED = 'USER_SIGNUP_FAILED';
const USER_SIGNUP_ERROR = 'USER_SIGNUP_ERROR';

const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
const USER_SIGNIN_FAILED = 'USER_SIGNIN_FAILED';
const USER_SIGNIN_ERROR = 'USER_SIGNIN_ERROR';

const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
const GET_MENU_FAILED = 'GET_MENU_FAILED';
const GET_MENU_ERROR = 'GET_MENU_ERROR ';

const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
const UPDATE_MENU_ERROR = 'UPDATE_MENU_ERROR ';

const POPULATE_MENU_SUCCESS = 'POPULATE_MENU_SUCCESS';
const POPULATE_MENU_ERROR = 'POPULATE_MENU_ERROR ';

const DELETE_MENU_SUCCESS =  'DELETE_MENU_SUCCESS';
const DELETE_MENU_ERROR =  'DELETE_MENU_ERROR';

const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS';
const GET_HISTORY_FAILED = 'GET_HISTORY_FAILED';
const GET_HISTORY_ERROR = 'GET_HISTORY_ERROR ';


const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
const GET_ORDERS_FAILED = 'GET_ORDERS_FAILED';
const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR ';

const ACCEPT_ORDERS_SUCCESS = 'ACCEPT_ORDERS_SUCCESS';
const ACCEPT_ORDERS_ERROR = 'ACCEPT_ORDERS_ERROR ';

const DECLINE_ORDERS_SUCCESS = 'DECLINE_ORDERS_SUCCESS';
const DECLINE_ORDERS_ERROR = 'DECLINE_ORDERS_ERROR ';


const COMPLETE_ORDERS_SUCCESS = 'COMPLETE_ORDERS_SUCCESS';
const COMPLETE_ORDERS_ERROR = 'COMPLETE_ORDERS_ERROR ';

const CLOUDINARY_IMAGE_UPLOAD_SUCCESS = 'CLOUDINARY_IMAGE_UPLOAD_SUCCESS';
const CLOUDINARY_IMAGE_UPLOAD_ERROR = 'CLOUDINARY_IMAGE_UPLOAD_ERROR';

const ORDER_MEAL_SUCCESS = 'ORDER_MEAL_SUCCESS';
const ORDER_MEAL_FAILED = 'ORDER_MEAL_FAILED';
const ORDER_MEAL_ERROR = 'ORDER_MEAL_ERROR ';

export {
    START_LOADING,
    STOP_LOADING,

    USER_SIGNUP_SUCCESS,
    USER_SIGNUP_FAILED,
    USER_SIGNUP_ERROR,

    USER_SIGNIN_SUCCESS,
    USER_SIGNIN_FAILED,
    USER_SIGNIN_ERROR,

    GET_HISTORY_SUCCESS,
    GET_HISTORY_FAILED,
    GET_HISTORY_ERROR,
   
    GET_MENU_SUCCESS,
    GET_MENU_FAILED,
    GET_MENU_ERROR,

    UPDATE_MENU_SUCCESS,
    UPDATE_MENU_ERROR,

    POPULATE_MENU_SUCCESS,
    POPULATE_MENU_ERROR,

    DELETE_MENU_SUCCESS,
    DELETE_MENU_ERROR,

    ORDER_MEAL_SUCCESS,
    ORDER_MEAL_FAILED,
    ORDER_MEAL_ERROR,

    GET_ORDERS_SUCCESS,
    GET_ORDERS_FAILED,
    GET_ORDERS_ERROR,

    ACCEPT_ORDERS_SUCCESS,
    ACCEPT_ORDERS_ERROR,

    DECLINE_ORDERS_SUCCESS,
    DECLINE_ORDERS_ERROR,

    COMPLETE_ORDERS_SUCCESS,
    COMPLETE_ORDERS_ERROR,

    CLOUDINARY_IMAGE_UPLOAD_SUCCESS,
    CLOUDINARY_IMAGE_UPLOAD_ERROR,
}