name: Run Tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
            echo "Running tests..."
            npm run test
        env:
            NODE_ENV: test
            DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}